### ISSUE TITLE
Back button doesn't save toggle

### ISSUE THREAD

**Issue by theixle** [seht/volumenotification#15]
After toggling a volume type on, pressing back button on device will not save toggle setting. 

Samsung S7 running Nougat.

Perhaps intended functionality but not expected for me. I expected back button to operate the same as back arrow in app.

**Comment by seht** [comment]
Unfortunately the phone's back button cannot be controlled in the same way as the back button in the app, however any changes should be reflected immediately without having to press the back button. (e.g. pressing the toggle button for each button, or swipping since the last update)

**Comment by digital-carver** [comment]
> however any changes should be reflected immediately without having to press the back button

They are and they aren't. For example, if I go into Call Volume, toggle it OFF, and press the back button, the actual notification changes immediately, but the app still shows it as being toggled ON. 

More importantly, if I go into the Call Volume again at that point, do nothing and press back, now the actual setting is changed to ON and the notification changes too.

Instead of going back into Call Volume, if I instead exited the app at that point and then opened again, then the UI is fine. 

The in-app back arrow has neither of those problems, but I wouldn't have guessed that that and the back button would behave differently if I didn't tinker around, would have assumed it was a basic app wide bug.

**Comment by seht** [comment]
This should've been fixed now.
Closing after deploying the first stable release. Enjoy 1.0.1 :-)
Please reopen if you find this issue again. Thank you!
