### ISSUE TITLE
Pls, make minSDK to 21(android5.0)!

### ISSUE THREAD

**Issue by DI555** [seht/volumenotification#33]
Pls, make down minSDK to 21(android5.0) or , at least , to 22(android5.1)!
Many of us used to use this app on android5.0/5.1, pls roll back to minSDK api 21, or at least 22!
Many thanks in advance!

**Comment by seht** [comment]
This would require reintroducing the notification. Since quick settings min version is Android N (API 24), So that is the minimum at the moment. Again, it would take a bit of work to try and make it backwards compatible, with the lastest androidx. Or it could be be out of scope. I will have to make an assessment. However, the previous release supported API 21 and is still available for [download, here](https://github.com/seht/volumenotification/releases/tag/v1.0.7-alpha3). Thanks!

**Comment by seht** [comment]
In progress: https://github.com/seht/volumenotification/tree/dev/baseup
(In the meanwhile, download an older version)
