### ISSUE TITLE
Pls, provide a legacy versions, Volume Notification!

### ISSUE THREAD

**Issue by DI555** [seht/volumenotification#34]
Pls, provide a legacy versions, Volume Notification!
In some cases and for those who used to use notifications for tune volume, pls support the legacy versions of Volume Notification!

Or, if you please, as an alternative, - inject an option to new versions of the app - with appeared volume control in Notifications!
So, each other would have a decigion to use Volumes in Tiles, use  it in Notification, or use its both!
Many thanks in advance!

**Comment by seht** [comment]
Thank you for reporting. The previous version is still available for download under releases. I will try including the notification again but it will take a bit more work, since it lost some compatibility with the required updates from androidx libraries, namely with background and foreground services. Thank you for your support and understanding.

**Comment by seht** [comment]
(Download here)[https://github.com/seht/volumenotification/releases/tag/v1.0.7-alpha3]

**Comment by seht** [comment]
Also, Google had just removed the app from the Play Store. This is why the update was rather urgent. Not that Google hadn't warned me well ahead of time. I had also stopped using Android... : >

**Comment by seht** [comment]
TODO/In progress: https://github.com/seht/volumenotification/tree/dev/baseup
